### ISSUE TITLE
Académie ?

### ISSUE THREAD

**Issue by TapsHTS** [Androz2091/pronote-bot-discord#1]
Yop ! Est-ce que l'académie de Aix Marseille fonctionne ?
car j'ai sa ? 
```
(node:31436) UnhandledPromiseRejectionWarning: TypeError: cas[casName] is not a function
    at getStart (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\pronote-api\src\auth.js:60:30)
    at Object.login (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\pronote-api\src\auth.js:15:25)
    at pronoteSynchronization (D:\Users\legot\Visual\pronote-bot-discord-master\index.js:50:35)
    at Client.<anonymous> (D:\Users\legot\Visual\pronote-bot-discord-master\index.js:96:5)
    at Client.emit (events.js:210:5)
    at WebSocketManager.triggerClientReady (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:210:5)
    at WebSocketShard.checkReady (D:\Users\legot\Visual\pronote-bot-discord-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
(node:31436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Androz2091** [comment]
Salut,
Pour le lien que tu m'as envoyé sur Discord, mets dans ton `.env`:
```
PRONOTE_CAS="none"
```
